# 012 Lets create some lists

In [74]:
MyFirstList = [3, 45, 56, 732]

In [75]:
MyFirstList

[3, 45, 56, 732]

In [76]:
type(MyFirstList)

list

In [77]:
l2 = ["hello", 24, True, 55.3]

In [78]:
l2

['hello', 24, True, 55.3]

In [79]:
l3 = ['how are you?', 55, MyFirstList]

In [80]:
l3

['how are you?', 55, [3, 45, 56, 732]]

In [81]:
#---

In [82]:
range(15)   #Python 3 - this is the same as xrange() in Python 2

range(0, 15)

In [83]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [84]:
x = [1, 2, 3, 4, 5, 6, 7]
x

[1, 2, 3, 4, 5, 6, 7]

In [85]:
y = list(range(8))
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [86]:
z = list(range(1,8))
z

[1, 2, 3, 4, 5, 6, 7]

In [87]:
z2 = list(range(100, 120))
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [88]:
w = list(range(100, 111, 2))
w

[100, 102, 104, 106, 108, 110]

In [89]:
w2 = list(range(100, 201, 10))
w2

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

---

# 013 Using the  brackets

In [90]:
w = ['a', 'b', 'c', 'd', 'e']

In [91]:
w

['a', 'b', 'c', 'd', 'e']

In [92]:
w[0]

'a'

In [93]:
w[1]

'b'

In [94]:
w[2]

'c'

In [95]:
len(w)

5

In [96]:
w[5]

IndexError: list index out of range

In [97]:
w[4]

'e'

In [98]:
w

['a', 'b', 'c', 'd', 'e']

In [99]:
# 0    1    2    3    4
#-5   -4   -3   -2   -1

In [100]:
w[-1]   #different behaviour to R

'e'

In [101]:
w[-3]

'c'

In [102]:
w[2]

'c'

In [103]:
#overwrite values:

In [104]:
w

['a', 'b', 'c', 'd', 'e']

In [105]:
w[2] = 63

In [106]:
w

['a', 'b', 63, 'd', 'e']

---

# 014 Slicing

In [107]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [108]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [109]:
letters[ : ]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [110]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [111]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [112]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [113]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [114]:
letters[-8:7]

['C', 'D', 'E', 'F', 'G']

In [115]:
letters[-8:-3]

['C', 'D', 'E', 'F', 'G']

In [116]:
#---- Advanced slicing

In [117]:
letters[2:9]

['C', 'D', 'E', 'F', 'G', 'H', 'I']

In [118]:
letters[2:9:2]

['C', 'E', 'G', 'I']

In [119]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [120]:
letters[::3]

['A', 'D', 'G', 'J']

In [121]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [122]:
letters[2:7:1]

['C', 'D', 'E', 'F', 'G']

In [123]:
letters[2:7:2]

['C', 'E', 'G']

In [124]:
letters[2:7:-1]

[]

In [125]:
letters[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [126]:
letters[6:1:-2]

['G', 'E', 'C']

# 015 Tuples in Python

In [127]:
#tuple = immutable list

In [128]:
t1 = (345, 674, 934)   #instead of square brackets, like lists, you use parentheses

In [129]:
t1

(345, 674, 934)

In [130]:
type(t1)

tuple

In [131]:
t1[0]

345

In [132]:
t1[1]

674

In [133]:
t1[1] = 45

TypeError: 'tuple' object does not support item assignment

# 016 Functions in Python

In [134]:
range(20,31)

range(20, 31)

In [135]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [136]:
mylist1 = list(range(20,31))

In [137]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [138]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [139]:
len(mylist1)

11

In [140]:
type(mylist1)

list

In [141]:
max(mylist1)

30

In [142]:
min(mylist1)

20

In [143]:
max(11,435,7)

435

# 017 Packages in Python

In [ ]:
import scrapy

In [ ]:
from scrapy.crawler import Crawlerprocess

In [147]:
import numpy

# 018 Numpy and Arrays in Python

In [148]:
l = [23245, 27, 546, 215, -1234]

In [149]:
l

[23245, 27, 546, 215, -1234]

In [150]:
import numpy as np

In [151]:
a = np.array(l)

In [152]:
a

array([23245,    27,   546,   215, -1234])

In [153]:
b = np.array([12, 455, 63.3, True, "abc"])

In [154]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [155]:
l.pop()

-1234

In [156]:
l

[23245, 27, 546, 215]

In [157]:
a.mean()

4559.8

In [158]:
# -----------------

In [159]:
a

array([23245,    27,   546,   215, -1234])

In [160]:
a[2:]

array([  546,   215, -1234])

In [161]:
a[2:4]

array([546, 215])

In [162]:
b = a[2:4]

In [163]:
b

array([546, 215])

In [164]:
b[0]

546

In [165]:
b[:] = 111

In [166]:
b

array([111, 111])

In [167]:
a

array([23245,    27,   111,   111, -1234])

In [168]:
c = a.copy()

In [169]:
c

array([23245,    27,   111,   111, -1234])

In [170]:
c[0] = 0

In [171]:
c

array([    0,    27,   111,   111, -1234])

In [172]:
a

array([23245,    27,   111,   111, -1234])

In [173]:
l

[23245, 27, 546, 215]

In [174]:
l[1:]

[27, 546, 215]

In [175]:
l[0:2]

[23245, 27]

In [176]:
l[::2]

[23245, 546]

In [177]:
#-----------

In [178]:
a

array([23245,    27,   111,   111, -1234])

In [179]:
a[2:]

array([  111,   111, -1234])

In [180]:
a[2:4]

array([111, 111])

In [181]:
b = a[2:4]

In [182]:
b

array([111, 111])

In [183]:
b[0]

111

In [184]:
b[:] = 111

In [185]:
b

array([111, 111])

In [186]:
a

array([23245,    27,   111,   111, -1234])

In [187]:
c = a.copy()

In [188]:
c

array([23245,    27,   111,   111, -1234])

In [189]:
c [0] = 0

In [190]:
a

array([23245,    27,   111,   111, -1234])

# 021 HOMEWORK Financial Statement Analysis

In [191]:
#Data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [192]:
#Calculate profit
profit = []
for i in range(0, len(revenue)):
    profit.append(revenue[i] - expenses[i])
profit

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [193]:
#Calculate tax
tax = [round(i*0.3, 2) for i in profit]
tax

[756.8,
 573.42,
 -1112.34,
 -874.29,
 -179.98,
 2179.57,
 2463.17,
 1183.49,
 998.52,
 -671.6,
 197.88,
 3488.86]

In [194]:
#Calculate profit after tax
profit_after_tax = []
for i in range(0, len(profit)):
    profit_after_tax.append(profit[i] - tax[i])
profit_after_tax

[1765.8700000000001,
 1337.9700000000003,
 -2595.4500000000007,
 -2040.0199999999995,
 -419.94000000000005,
 5085.67,
 5747.380000000001,
 2761.4800000000005,
 2329.8699999999994,
 -1567.0500000000015,
 461.71999999999855,
 8140.68]

In [195]:
#Calculate profit margin
profit_margin = []
for i in range(0, len(profit)):
    profit_margin.append(profit_after_tax[i] / revenue[i])
profit_margin

#Round to 2 decimal points, then multiply by 100 to get %
profit_margin = [round(i*100, 2) for i in profit_margin]
profit_margin

[12.12,
 17.59,
 -30.14,
 -22.23,
 -5.21,
 62.74,
 49.99,
 28.28,
 22.61,
 -10.9,
 4.31,
 52.75]

In [196]:
#Calculate the mean profit after tax for the 12 months
mean_pat = sum(profit_after_tax) / len(profit_after_tax)
mean_pat

1750.6816666666666

In [197]:
#Find the months with above-mean profit after tax
good_months = []
for i in range(0, len(profit)):
    good_months.append(profit_after_tax[i] > mean_pat)
good_months

[True, False, False, False, False, True, True, True, True, False, False, True]

In [198]:
#Bad months are the opposite of good months!
bad_months = []
for i in range(0, len(profit)):
    bad_months.append(profit_after_tax[i] < mean_pat)
bad_months

[False, True, True, True, True, False, False, False, False, True, True, False]

In [199]:
#The best month is where profit after tax was equal to the maximum
best_month = []
for i in range(0, len(profit)):
    best_month.append(profit_after_tax[i] == max(profit_after_tax))
best_month

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [200]:
#The worst month is where profit after tax was equal to the minimum
worst_month = []
for i in range(0, len(profit)):
    worst_month.append(profit_after_tax[i] == min(profit_after_tax))
worst_month

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [201]:
#Convert all calculations to units of one thousand dollars
revenue_1000 = [round(i/1000, 2) for i in revenue]
expenses_1000 = [round(i/1000, 2) for i in expenses]
profit_1000 = [round(i/1000, 2) for i in profit]
profit_after_tax_1000 = [round(i/1000, 2) for i in profit_after_tax]

revenue_1000 = [int(i) for i in revenue_1000]
expenses_1000 = [int(i) for i in expenses_1000]
profit_1000 = [int(i) for i in profit_1000]
profit_after_tax_1000 = [int(i) for i in profit_after_tax_1000]

In [202]:
#Print Results
print ("Revenue :") 
print (revenue_1000)
print ("Expenses :") 
print (expenses_1000)
print ("Profit :")
print(profit_1000)
print ("Profit after tax :")
print (profit_after_tax_1000)
print ("Profit margin :")
print (profit_margin)
print ("Good months :")
print (good_months)
print ("Bad months :")
print (bad_months)
print ("Best month :")
print (best_month)
print ("Worst month :")
print (worst_month)

Revenue :
[14, 7, 8, 9, 8, 8, 11, 9, 10, 14, 10, 15]
Expenses :
[12, 5, 12, 12, 8, 0, 3, 5, 6, 16, 10, 3]
Profit :
[2, 1, -3, -2, 0, 7, 8, 3, 3, -2, 0, 11]
Profit after tax :
[1, 1, -2, -2, 0, 5, 5, 2, 2, -1, 0, 8]
Profit margin :
[12.12, 17.59, -30.14, -22.23, -5.21, 62.74, 49.99, 28.28, 22.61, -10.9, 4.31, 52.75]
Good months :
[True, False, False, False, False, True, True, True, True, False, False, True]
Bad months :
[False, True, True, True, True, False, False, False, False, True, True, False]
Best month :
[False, False, False, False, False, False, False, False, False, False, False, True]
Worst month :
[False, False, True, False, False, False, False, False, False, False, False, False]
